### ISSUE TITLE
Media browser - enable browsing of existing files when adding images to pages

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#138]
- [x] Someone to show Recia and Steph how this works
- [x] Add ability to browse existing files within the website when uploading a 'new' image to a page
- [ ] Roll out to all areas of the site
- [ ] Fix issue described below by Steph (sorry, i didn't quite understand it)

**Comment by russ-manta** [comment]
@meldera is it possible to use this module for this? https://www.drupal.org/project/filefield_sources

**Comment by meldera** [comment]
@russ IMCE won't work with paragraph fields. Only autocomplete could be considered if such experience would be acceptable.

**Comment by russ-manta** [comment]
@StephMSlack @angievanhegan  the only way we can do this is to add an autocomplete field to the image upload field which means you can add existing images providing you know the name of the image file - see the example in the attached 'Existing file auto-complete' - does this work for you?
![filefield-sources](https://user-images.githubusercontent.com/25846670/36905444-4534a5f8-1e2b-11e8-818c-e4a04fbb2e69.png)

**Comment by StephMSlack** [comment]
@russ-manta I need to show this to Recia and get her thoughts as she will be the one using the system on a daily basis. Is there somewhere in drupal that I can have a look/try how it works?

**Comment by StephMSlack** [comment]
@russ-manta - from Recia
Hopefully Recia has interpreted your comment correctly (see below). If so, then yes, that should be fine.
If you have a few minutes to talk through it this afternoon, that would be helpful as well. 

"This looks okay, I think. I’m prepared to try anything that doesn’t involve uploading the same image over and over again. If I understand Russ correctly, we will just need to keep a centrally accessible list of images that are in the media centre, so that authors can trigger the auto-complete.
Recia"

**Comment by russ-manta** [comment]
@StephMSlack I've now added this functionality to the image field on the Conten block nugget. If you create some content with a Content block you should see a link for 'reference existing' on the image field.  Click this and start entering a file name (just type 'a') in the autocomplete field to select an existing image and then crop etc as normal.  See what you think..
![select-existing-image](https://user-images.githubusercontent.com/25846670/37155856-4e1af342-22dc-11e8-8b74-7fe29e8a75f7.jpg)

**Comment by russ-manta** [comment]
@StephMSlack I've now created you a folder called 'images' within the content folder and you can browse this when adding a new image to a content block and upload an image here at the same time if adding a completely new one.  It's currently only on the content block nugget but we can roll it out further once you confirm you are happy with ti

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan thanks for this. I tried adding an image from the file manager into a content block in the policy and media section. The file manager showed an images folder, but I couldn't access the image I had uploaded previously. Not sure if this issue is because I am trying to use the functions in a different content type? The ability to browse for the file was available and I could get to the file manager, but couldn't get to the image file higher in the directory. 
![screen shot 2018-03-21 at 13 05 48 2](https://user-images.githubusercontent.com/32127102/37711456-b2c29102-2d08-11e8-959d-eb034645e6b0.png)

![screen shot 2018-03-21 at 13 07 54](https://user-images.githubusercontent.com/32127102/37711518-edf63f08-2d08-11e8-8c48-9e64b6cd9de2.png)

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan aside from the above, happy with how it functions and how you can preview things. I managed to add an image to the file manager and could add that image to a content block in a new resource I was creating. 
![screen shot 2018-03-21 at 13 12 03 2](https://user-images.githubusercontent.com/32127102/37711735-96bacadc-2d09-11e8-9e72-a235bdd0db4e.png)

**Comment by russ-manta** [comment]
@StephMSlack @angievanhegan  @dilwarhussain I think the issue here is we only set the functionality up on the content block nugget for you to test. If you are happy with that then we just need to roll it out further to the card content image and other image fields

**Comment by dilwarhussain** [comment]
Hey @StephMSlack I've rolled this functionality out to all the image files. Please try and let me know if it is working as desired, thanks.

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain, this seems to be working fine.
