### ISSUE TITLE
COSTING: CiviCRM Past events - import from live site

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#281]
Note from Steph: the priority will be the current events that will be open for booking (there are 13)
Steph to confirm the number of past events being migrated over over from Etouches. This can be done after go live
# Done criteria
- [x] Create events in Drupal automatically based on events from live Civi

**Comment by angievanhegan** [comment]
@StephMSlack FYI

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan there are now 14 live events. If you can let me know the level of work required to create the events in drupal and a cost that would be great.

**Comment by russ-manta** [comment]
@StephMSlack I think we would make these 14 live events by hand.  It would probably take a couple of hours at most.  You would still need to add any drupal content afterwards of course.  Is there anywhere we can see these events?

**Comment by StephMSlack** [comment]
@russ-manta some of the events have been created in the live site at the moment, the rest are on our system e-touches.

The issue is making sure we import the participants across from the current system we use and that the event links to the correct drupal page. If you are going to be creating them by hand, we can look at doing that here and creating the event once drupal is linked to our live Civi database and then reimport the participants. (I was hoping there might be an easier way with code!)

I know we would have to add the drupal information after that. 

G4J ID 89
British Geriatrics Society Autumn Meeting 2018 ID 70
Mersey Region Autumn 2018   (ID: 90)
Yorkshire Region Autumn 2018   (ID: 91)
Falls 2018  (ID: 83)

on e-touches (as an example)
https://eu.eventscloud.com/ehome/index.php?eventid=200178913&
https://eu.eventscloud.com/ehome/index.php?eventid=200178901&

If it easier to chat the pros/cons through, let me know

**Comment by StephMSlack** [comment]
@russ-manta An update - could you manually link the 5 events that have already been created in the live version of Civi? Geraint is worried that deleting the events and participants will not delete the contributions that have already been added. 

They are:
G4J ID 89
British Geriatrics Society Autumn Meeting 2018 ID 70
Mersey Region Autumn 2018 (ID: 90)
Yorkshire Region Autumn 2018 (ID: 91)
Falls 2018 (ID: 83)

BGS will create remaining events in civi post go-live.

**Comment by StephMSlack** [comment]
thanks @russ-manta 
@angievanhegan this has been done
