### ISSUE TITLE
Create view for SIGs tagged by topic.[BGS: P2]

### ISSUE THREAD

**Issue by mrm-git** [MantaRayMedia/bgs#371]
Create new tab for SIGs with the label 'BGS groups' (to be placed after blogs in the tab order) SIGs to be listed using card content (as with the rest of the content in topics)

# Done criteria
* [x] Create view - duplicate existing display
* [x] Theme as per SIGs on BGS Groups page

- - -
**parents:**

1. https://trello.com/c/bXfw3Bxu

**Comment by russ-manta** [comment]
@cutlern Nelle should we be displaying images on the card here for SIGs? http://bgs-staging.mrmdev2.co.uk/topics/cga-in-acute-settings like on this page? http://bgs-staging.mrmdev2.co.uk/bgs-groups

**Comment by cutlern** [comment]
@russ-manta done!

**Comment by conferences-BGS** [comment]
@russ-manta DOn't follow this ticket and when looking at http://bgs-staging.mrmdev2.co.uk/bgs-groups the images are broken 
![image](https://user-images.githubusercontent.com/40232743/48677345-50893f00-eb6b-11e8-877a-e34ddbf47293.png)

Not sure why this ticket exists as in live site we have 
![image](https://user-images.githubusercontent.com/40232743/48677353-6b5bb380-eb6b-11e8-8390-576e5a873806.png)

**Comment by russ-manta** [comment]
@cutlern can you change the tab title to 'BGS groups' please?

**Comment by cutlern** [comment]
@russ-manta done :)

**Comment by angievanhegan** [comment]
Sorry @conferences-BGS it wasn't very clear. The change here is to add a tab for the SIG on the topics landing page:  http://bgs-staging.mrmdev2.co.uk/topics/cardiovascular

Because there is an image for the SIG on the live site, the image will appear above the SIG title. 
![sig on topic page](https://user-images.githubusercontent.com/3796718/48684527-052d5b80-eb80-11e8-8b57-2f9410c16f55.PNG)

**Comment by conferences-BGS** [comment]
@angievanhegan OK approved - please push to live
