### ISSUE TITLE
Create visual designs for About us pages

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#44]
# Done criteria/BGS review criteria
- [x] [Masthead and navigation](https://invis.io/4EDQ458R5#/261765900_About_Us) 
   - [x] **ISSUE** Can there be slightly more space between the bottom of the logo before the lighter colour of the navigation begins (assuming it looks ok)
   - [x] **ISSUE** Add FB icon to mast head
- [ ] Select fonts: 
  - [x] [Option A](https://invis.io/4EDQ458R5#/263586181_Our_Purpose_W-Content)
  - [ ] [Option B](https://invis.io/4EDQ458R5#/263597595_Our_Purpose_-_Caslon_Body_W-Content)
- [x] [Landing page](https://invis.io/U3EAE9BW9)
- [x] [Content page](https://invis.io/3PEAE33G4)
   - [x] **ISSUE** Can we try adding an [image to the PDF download on the RHS](https://invis.io/4XEFPWI2B)? (Please note comment from 14/11/17)
- [x] [Person page](https://invis.io/KUEAEFQWN)
- [x] [Governance (team) page](https://invis.io/FWEFPVKRA)
- [x] [Footer](https://invis.io/4XEFPWI2B)
- [x] [Mobile layout](https://invis.io/2PEFPWPDN)

**Comment by angievanhegan** [comment]
@cat-manta When you've done all these, please can you untick all the done criteria and assign this issue to @StephMSlack so she can tick the boxes to confirm she's happy with them. Thanks

**Comment by StephMSlack** [comment]
**Masthead**
There was a query about accessibility and how easy it is to read the navigation when on the lighter purple. Would be curious to see how it worked with only one colour rather than 2.

**Navigation**
Is it possible to restrict the length of the navigation text so it doesn't event move to go underneath the the logo or strapline? 

**Fonts** 
would it be possible to increase the font size slightly, and a slightly greater increase for the Casalon version? the debate is continuing, but there are concerns about legibility (this may also be a result of seeing a page in invision v's online)

A**bout us page**
Like the pink as the highlight colour (not purple, it becomes too much)
like the rounded edges for the boxes 
There are 2 versions of the 4 across boxes - we are leaning towards the 2nd version, but maybe with a little more white space between boxes?
Like how the boxes display 2 across and 1 across 

**Social Media icons**
These appear in multiple places - I have assumed that the option in the masthead and footer are to encourage users to follow us, where as the icons at the side of the 'our purpose' page are for users to share the page content. Is this correct? If so, we may need to label the ones at the side in a clearer way. Maybe the share icon 
Could we add email and print options to the side social media and lose G+

happy with the video nugget and image nugget

like the quotes function

**Our Purpose page**
Boxes on RHS
Is there a limit to how many options/links that we could add within the box? Eg could we have 3 links for related content and 6 attachments listed. If not - should we set a limit to maintain the integrity of the design?
Can the boxes:
- contain more than 2-3 lines of text per link?
- have images within them (eg is the attachment is a printed document, we would have the document cover art that we could add here)

in the related content box, could we specify what type of document it is (blog, news, resource etc)

Are these boxes set to the top right of the page? And what is the impact visually of increasing their length if we add lots of text to them?

FAQ nuggets - what is the impact of using these on site metrics

Person page 
Might not use the follow me nugget in this way, but would potentially be worth adding an email address to this section so members can contact our committee members. 

Might want to add a new box - other articles by...
Rather than related content could we show other pages that the person has written on the site. Something that shows up automatically if they have written a blog post or a resource

**Comment by cat-manta** [comment]
**Masthead**
I have done an alternative version of the header on the [Governance page](https://invis.io/4EDQ458R5#/263039958_Governance), however white text on the lighter purple is fully accessible, so we would recommend the current version of the header.


**Nav**
We can restrict the length of navigation, however we would advise against this as it would mean the header would need to change to a mobile menu on smaller laptop screens. I have uploaded a [mobile design](https://invis.io/4EDQ458R5#/263100508_Our_Purpose_-_Mobile) so you can see what the header would look like. Restricting the width of the navigation would rely on short navigation titles, so if you ever changed them the navigation would likely break, meaning that the titles might end up on top of each other. Happy to discuss this or any of the other points with you in a call if it would be useful.


**Fonts**
Could you have a look at [this site](https://www.alnap.org/blogs/8-things-we-learned-from-our-work-on-evidence-this-year) to see what you think of the body size? The body text, although a different font, is the same size as the body font in the BGS design, so is a better representation of how the text would look on the live site.

I have increased the size and character width of the caslon body text, and have also added real content from the current BGS site for [this new mockup](https://invis.io/4EDQ458R5#/263597595_Our_Purpose_-_Caslon_Body_W-Content), and added the same content to [the sans serif version](https://invis.io/4EDQ458R5#/263586181_Our_Purpose_W-Content). I think this will really help deciding which body font is preferred/legible as the content makes sense. It's also worth mentioning that font size is fairly simple to change so it can be altered at any time.


**Box links**
I have made a new [governance page](https://invis.io/4EDQ458R5#/263039958_Governance) with more space in between boxes.


**Social media icons**
I have added a label to the share icons on the new 'Our Purpose' page with real content.
RE adding print and email icons - it's a bit dated to add these buttons so we wouldn't recommend it.


**Our purpose page**
There are no limits, so it's down to the content editor to not overload the page, and it would be better not to limit them for the occasional time where a lot of attachments are required etc.

The related content section isn't finalised but I have updated the new designs so they are more representative of what would be there e.g. a related blog would have a tag, title and date.

It's possible to automatically include images if the attachment is a PDF, however due to the size of the thumbnail they wouldn't look very good, and you might need to crop the image which would increase your workload.

Yes you can specify the type of document.

Yes the boxes are set to top right. I think there will be a wysiwyg nugget that can go in the RHS so you can enter whatever text you like here, however we would advise against entering too much here as it's meant to simply be extra info.

FAQ - Russ will look into this

Person - I have added a contact me section with an email icon

Other articles by... - This is possible but Angie needs to confirm whether this is in scope when we look at related content.

**Comment by angievanhegan** [comment]
@StephMSlack I've moved this into your column for you to sign off. Thanks

**Comment by StephMSlack** [comment]
**Masthead** 
Yes, go with the first version with two colours (navigation the lighter purple)

Can there be slightly more space between the bottom of the logo before the lighter colour of the navigation begins? just to give more prominence to the logo should the navigation extend the length of the page (assuming this looks OK from a visual point of view)

**Navigation** 
We will combine Clinical Quality Resources and Research resources into one 'resources' section.

Do not need to restrict the width of the navigation. 

Mobile design is fine 

Query re: logo/strapline and whether it would appear on a tablet version

**Font**
Use Source Sans (do not use Adobe Casalon)
Font size (as referenced to ALNAP) is fine

**Social Media**
Add Facebook to top SM navigation (with twitter & linked in). Concern re the icons removing the prominence/importance of join us/login.

Our purpose - nuggets on RHS
Could it be optional to include the image from the cover of an attachment?

**Comment by StephMSlack** [comment]
Hi @cat-manta and @angievanhegan I've managed to get sign off for the above. A few additional comments/questions but hopefully they dont impact the development too much. Steph

**Comment by angievanhegan** [comment]
Actually @cat-manta before we move this to done, there's a couple of minor things for you to do.

**Comment by cat-manta** [comment]
@StephMSlack @angievanhegan I have updated the header designs with more space above and below the logo and added the facebook icon.

**Comment by angievanhegan** [comment]
@StephMSlack The first two issues are all ready for you to sign off - Cat's still working on the PDF change. If you can sign these off and move it back to the In progress column (and take yourself off as assigned, that would be great). Thanks

**Comment by StephMSlack** [comment]
@angievanhegan I had ticked and completed the first two issues this morning (not sure why it didnt save!). completed now

**Comment by cat-manta** [comment]
@StephMSlack I have updated [Our Purpose](https://invis.io/4EDQ458R5#/263586181_Our_Purpose_W-Content) to include attachment images. The smaller image works better, however long titles become difficult to read as the width is so narrow. I have included the same long title on the current attachment design to compare.

**Comment by StephMSlack** [comment]
Hi @cat-manta Thanks for this. Yes, please go with the smaller image. I assume when there is no image uploaded it will look like the original design? We will ensure that the titles for attachments are shorter so that they are readable.

**Comment by angievanhegan** [comment]
@cat-manta I put this back into the 'in progress' column so that you can update the design so it only shows the one they'll use.
